### ISSUE TITLE
versionCode doesn't get bumped automatically

### ISSUE THREAD

**Issue by tibbe** [r0adkll/upload-google-play#105]
This is a feature request.

The biggest hurdle to automating uploads to Play Store using this action is that you manually need to bump `versionCode` every time. This is easy to forget to do in every commit. Could that be automated? Is it possible to fetch the current `versionCode` from the Play Store API?

**Comment by boswelja** [comment]
Bumping the version code automatically would be impossible since we require an aab (or apk) that has already been built, but version code needs to be set at compile time. 

If you're interested, I've been using this action to generate a version, which gets passed to Gradle, upload-google-play and a GH releases action
https://github.com/codacy/git-version
