### ISSUE TITLE
How to set up uploading screenshots?

### ISSUE THREAD

**Issue by bhargavms** [r0adkll/upload-google-play#126]
Is it possible to upload screenshots in a similar way that we upload whatsnew from whatsnewdirectory ?

**Comment by boswelja** [comment]
Not currently, I'd argue that would be the responsibility of a separate action, since screenshots are tied to store listing rather than releases.

I just had a quick look at the API docs and it doesn't look like editing the listing is currently supported either (docs here: https://developers.google.com/android-publisher/api-ref/rest/v3/edits)

**Comment by boswelja** [comment]
Closing this. A separate action makes sense, our scope here is (currently) "upload a release"
