### ISSUE TITLE
Excessive permissions recommended?

### ISSUE THREAD

**Issue by lacop11** [r0adkll/upload-google-play#224]
Hey, I wonder why the instructions suggest giving the service account "owner" on the project. That is very unsafe and is excessive.

I actually got this working without any permissions at all - as far as I can tell the service account just needs to be added in Play Store to have permissions to publish the app, but on GCP IAM level no permissions are required. Maybe that is for features I'm not using?

I would recommend updating the README to not ask people to just give such broad permissions to the account. Happy to send a PR if you agree.

Additionally I would highlight the fact no secret json is required and workload identity can be used: https://github.com/r0adkll/upload-google-play/issues/146#issuecomment-1258394269

**Comment by boswelja** [comment]
Seems reasonable, as long as we are 100% sure it works fine without

**Comment by lacop11** [comment]
Work without problems in my testing, and the API docs only ask you to give the service account permissions within Google Play Console, not in GCP: https://developers.google.com/android-publisher/getting_started#service-account

**Comment by albnok** [comment]
I'm using Workload identity authentication flow* and getting this error:

```
Creating a new Edit for this release
Error: Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).
```

* I could not figure out what to add for [the last step](https://github.com/google-github-actions/auth#:~:text=As%20needed%2C%20allow%20authentications%20from%20the%20Workload%20Identity%20Pool%20to%20Google%20Cloud%20resources.)

I tried 3.iv. granting permissions to "Release to production", then I even tried giving the service account Admin permissions, but the same error persists. Is it still working on your end? Or is it due to the last step?

**Comment by Bwvolleyball** [comment]
@albnok - are you able to elaborate a bit more about what you did to fix this? I'm struggling with this error as well, and I'd love to be able to update the readme if possible to this project to help the next person.
