### ISSUE TITLE
releaseName output undefined

### ISSUE THREAD

**Issue by boswelja** [r0adkll/upload-google-play#49]
Seems the releaseName output is undefined, any idea what could be causing that? I've tried playing around with it on a local branch but can't seem to figure it out.

**Comment by r0adkll** [comment]
Per issue #48, the call to fetch the release name from the API after committing it was causing this failure so I changed the implementation to try and fetch the release name from the response of adding the release to the edit, but now I suppose that doesn't get populated until it gets committed. Let me dig into the API more and see what I can do about properly generating this output and let me set up a more robust testing environment so I can verify these changes since I don't have any active projects to test releases at this moment.

**Comment by boswelja** [comment]
Oh interesting, I've tried moving the same call to before the commit is made in a local fork and it still returns undefined, so it seems like Google Play doesn't want to tell us about the release once it's created?

**Comment by r0adkll** [comment]
Closing this per the conversation on #51. We can revisit this if and when Google updates or addresses the ability to pull this information.
