### ISSUE TITLE
userFraction for 100% rollout not working

### ISSUE THREAD

**Issue by kunal26das** [r0adkll/upload-google-play#65]
Error: A provided userFraction must be between 0.0 and 1.0, inclusive-inclusive

Tried setting userFraction to 1 and 1.0, with and without quotes

**Comment by r0adkll** [comment]
If you refer to the [README.md](https://github.com/r0adkll/upload-google-play/blob/master/README.md)

> Portion of users who should get the staged version of the app. Accepts values between 0.0 and 1.0 (exclusive-exclusive). **Omitting this value will execute a full rollout.**

if you omit the user fraction from your workflow config it will perform a full rollout. I can't remember the precise reason I set it up this way, probably because of this exact issue, but if you omit the value it should work as desired.
