### ISSUE TITLE
Auto-increment version code

### ISSUE THREAD

**Issue by cachapa** [r0adkll/upload-google-play#68]
One of the features I really like about  Gradle Play Publisher is the ability to auto-increment the version code: https://github.com/Triple-T/gradle-play-publisher#handling-version-conflicts

Would it be possible for this action to implement similar functionality? Version codes have no meaning in my release workflow so I just want to automate it in a way that avoids conflicts.

**Comment by vpmalley** [comment]
Looking for the same feature.
Given that the versionCode is supposed to be set before the bundle phase, this is probably worth another action, not a feature of the upload action.

**Comment by r0adkll** [comment]
@vpmalley Is correct. This would not be even possible with this action since the bundle/apk is already built. Gradle Play Publisher is able to accomplish this because it's a Gradle plugin and can add this process to the build steps. 

I would suggest finding or creating another action to accomplish this or implementing a versioning schema to avoid the problem all together. Something like this (https://gist.github.com/passsy/5ea60bce2ed395a9593ef27d8c186ad2) where the versionCode is generated automatically based on your version name if you follow semantic versioning.

**Comment by cachapa** [comment]
That does make sense, thanks for the update.
